merge mandriva changes

diff --git a/service b/service
--- a/service
+++ b/service
@@ -1,80 +1,155 @@
 #!/bin/sh
+# -*- Mode: shell-script -*-
+# Copyright (C) 2001 by Chmouel Boudjnah <chmouel@mandrakesoft.com>
+#			MandrakeSoft.
+# Redistribution of this file is permitted under the terms of the GNU
+# Public License (GPL)
+# Original version writen by RedHat.
+
+debug=
+service=
+opt=
+fullrestart=
+fullrestartall=
+statusall=
+
+servicedir=/etc/init.d
+xinetddir=/etc/xinetd.d
+
+basename=${0##*/}
 
 . /etc/init.d/functions
 
-VERSION="$(basename $0) ver. 1.1"
-USAGE="Usage: $(basename $0) < option > | --status-all | \
-[ service_name [ command | --full-restart ] ]"
-SERVICEDIR="/etc/init.d"
-ACTIONDIR="/usr/libexec/initscripts/legacy-actions"
-SERVICE=
-ACTION=
-OPTIONS=
+service_available () {
+	local subsys
+	cd $servicedir
 
-if [ $# -eq 0 ]; then
-   echo "${USAGE}" >&2
-   exit 1
-fi
+	for subsys in *;do
+		case $subsys in
+			kheader|numlock|sound|usb|netfs|kudzu|local|pcmcia| \
+			network|local|dm|harddrake|xfs) continue;;
+		esac
+		is_ignored_file "$service" && continue
+		grep -q chkconfig $subsys || continue
+		egrep -q 'restart.*\)' $subsys || continue
+		[[ -x $subsys ]] || continue
+		[[ -e /var/lock/subsys/$subsys ]] || continue
+		echo $(egrep -a '^#.*chkconfig: ' $subsys|awk '{print $4}') $subsys
+	done | sort -n|cut -d" " -f2
+}
 
-cd /
-while [ $# -gt 0 ]; do
-  case "${1}" in
-    --help | -h | --h* )
-       echo "${USAGE}" >&2
-       exit 0
-       ;;
-    --version | -V )
-       echo "${VERSION}" >&2
-       exit 0
-       ;;
-    --ignore-dependencies)
-       export SYSTEMCTL_IGNORE_DEPENDENCIES=1
-       shift
-       ;;
-    --skip-redirect)
-       export SYSTEMCTL_SKIP_REDIRECT=1
-       shift
-       ;;
-    *)
-       if [ -z "${SERVICE}" -a $# -eq 1 -a "${1}" = "--status-all" ]; then
-          cd ${SERVICEDIR}
-          for SERVICE in * ; do
-            case "${SERVICE}" in
-              functions | halt | killall | single| linuxconf| kudzu)
-                  ;;
-              *)
-                if ! is_ignored_file "${SERVICE}" \
-		    && [ -x "${SERVICEDIR}/${SERVICE}" ]; then
-                  env -i PATH="$PATH" TERM="$TERM" "${SERVICEDIR}/${SERVICE}" status
-                fi
-                ;;
-            esac
-          done
-          exit 0
-       elif [ $# -eq 2 -a "${2}" = "--full-restart" ]; then
-          SERVICE="${1}"
-          if [ -x "${SERVICEDIR}/${SERVICE}" ]; then
-            env -i PATH="$PATH" TERM="$TERM" "${SERVICEDIR}/${SERVICE}" stop
-            env -i PATH="$PATH" TERM="$TERM" "${SERVICEDIR}/${SERVICE}" start
-            exit $?
-          fi
-       elif [ -z "${SERVICE}" ]; then
-         SERVICE="${1}"
-       elif [ -z "${ACTION}" ]; then
-         ACTION="${1}"
-       else
-         OPTIONS="${OPTIONS} ${1}"
-       fi
-       shift
-       ;;
-   esac
+usage () {
+	cat <<EOF 1>&2
+Usage: $basename -[Rfshv] SERVICE ARGUMENTS
+	-f|--full-restart:	Do a fullrestart of the service.
+	-R|--full-restart-all:	Do a fullrestart of all running services.
+	-s|--status-all:	Print a status of all services.
+	--ignore-dependencies:  Do not start required systemd services
+	--skip-redirect:	Do not redirect to systemd
+	-d|--debug:		Launch with debug.
+	-h|--help:		This help.
+EOF
+exit 1
+}
+check_if_inetd() {
+    local serv=$1
+    if [[ ! -f ${servicedir}/${serv} ]];then
+	if [[ -f ${xinetddir}/${serv} ]];then
+	    if egrep -q ".*disable.*yes.*" ${xinetddir}/${serv};then
+		echo "$serv is a xinetd service and it is disabled"
+		echo "to activate it do the following command:"
+		echo "chkconfig ${serv} on"
+		service=
+		return
+	    fi
+	    service=xinetd
+	    [[ $options = "start" ]] && options=reload
+	    if [[ $options != reload ]] && [[ -z $fullrestart ]];then
+		echo "There is no such option for xinetd services"
+		echo "You can only use the start option to reload a xinetd service"
+		service=
+	    fi
+	    echo "${serv} is a xinetd service"
+	fi
+    fi
+    return
+}
+
+while [[ $1 = --* ]] || [[ $1 = -* ]];do
+    opt=$1
+    shift
+    case $opt in
+	--full-restart|-f) fullrestart=yes;;
+	--full-restart-all|-R) fullrestartall=yes;;
+	--status-all|-s) statusall=yes;;
+	--debug|-d) set -x ; debug="/bin/bash -x";;
+	--help|-h) usage;;
+	--ignore-dependencies) export SYSTEMCTL_IGNORE_DEPENDENCIES=1;;
+	--skip-redirect) export SYSTEMCTL_SKIP_REDIRECT=1;;
+	*) echo "Unknow option $opt"; usage;
+    esac
 done
 
-if [ -f "${SERVICEDIR}/${SERVICE}" ]; then
-   env -i PATH="$PATH" TERM="$TERM" SYSTEMCTL_IGNORE_DEPENDENCIES=${SYSTEMCTL_IGNORE_DEPENDENCIES} SYSTEMCTL_SKIP_REDIRECT=${SYSTEMCTL_SKIP_REDIRECT} "${SERVICEDIR}/${SERVICE}" ${ACTION} ${OPTIONS}
-elif [ -x "${ACTIONDIR}/${SERVICE}/${ACTION}" ]; then
-   env -i PATH="$PATH" TERM="$TERM" SYSTEMCTL_IGNORE_DEPENDENCIES=${SYSTEMCTL_IGNORE_DEPENDENCIES} SYSTEMCTL_SKIP_REDIRECT=${SYSTEMCTL_SKIP_REDIRECT} "${ACTIONDIR}/${SERVICE}/${ACTION}" ${OPTIONS}
+service=${1##*/}; shift;
+options="$@"
+
+#nuts ? (yes)
+while :;do
+    [[ -z $service && -n $statusall ]] && break
+    [[ -z $service && -n $fullrestartall ]] && break
+    [[ -n $service && -n $statusall ]] && { echo "--status-all doesn't need arguments"; usage ;}
+    [[ -n $service && -n $fullrestartall ]] && { echo "--full-restart-all doesn't need arguments"; usage ;}
+    [[ -z $service ]] && usage
+    [[ -n $service ]] && break
+
+done
+
+if [[ -n $fullrestartall ]];then
+    for subsys in $(service_available);do $0 -f $subsys;done
+    exit 0 #for glibc post upgrades
+fi
+
+if [[ -n $statusall ]];then
+    cd $servicedir
+    for service in *;do
+	case $service in
+	    functions | halt | killall | single| linuxconf| kudzu | \
+		mandrake_firstime | mandrake_everytime)
+		continue ;;
+	esac
+	is_ignored_file "$service" && continue
+	if egrep -q '^([^#]*)status\)' $service;then
+	    $debug $servicedir/$service status
+	fi
+    done
+    exit 0;
+fi
+
+if [[ -n $fullrestart ]];then
+    check_if_inetd "$service"
+    cd "$servicedir"
+    if [[ -f ./$service ]];then
+	$debug ./$service stop
+	$debug ./$service start
+	exit $?
+    else
+	echo "Cannot find $servicedir/$service"
+	usage
+    fi
+    exit 1
+fi
+
+[[ -z $options ]] && { echo -e "I need an action\n" 1>&2; usage;}
+
+check_if_inetd "$service" ; [[ -z $service ]] && exit 1
+
+if ! is_ignored_file "$service" && [[ -f $servicedir/$service ]]; then
+    env -i PATH="$PATH" TERM="$TERM" SYSTEMCTL_IGNORE_DEPENDENCIES=${SYSTEMCTL_IGNORE_DEPENDENCIES} SYSTEMCTL_SKIP_REDIRECT=${SYSTEMCTL_SKIP_REDIRECT} $debug "$servicedir/$service" $options
+    exit $?
+elif [[ -f /lib/systemd/system/"$service".service ]] && /bin/mountpoint -q /sys/fs/cgroup/systemd; then
+    [ -c /dev/stderr ] && echo $"Redirecting to /bin/systemctl ${options} ${service}.service" > /dev/stderr
+    exec /bin/systemctl ${options} ${service}.service
 else
-   echo $"Redirecting to /bin/systemctl ${ACTION} ${OPTIONS} ${SERVICE}.service" >&2
-   exec /bin/systemctl ${ACTION} ${OPTIONS} ${SERVICE}.service
+    echo "Cannot find $service service"
+    usage
 fi
diff --git a/sysconfig/network-scripts/ifup-eth b/sysconfig/network-scripts/ifup-eth
--- a/sysconfig/network-scripts/ifup-eth
+++ b/sysconfig/network-scripts/ifup-eth
@@ -15,21 +15,33 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
 
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+TEXTDOMAIN=initscripts
+
 . /etc/init.d/functions
 
 cd /etc/sysconfig/network-scripts
 . ./network-functions
 
-[ -f ../network ] && . ../network
+[ -f /etc/sysconfig/network ] && . /etc/sysconfig/network
 
 CONFIG=${1}
+boot=${2}
+daemon=
+[ "foo${boot}" = "fooboot" -o "foo${boot}" = "foodaemon" ] && daemon=1
 
 need_config "${CONFIG}"
 
 source_config
 
+# Old BOOTP variable
+if [ "${BOOTP}" = "yes" ]; then
+    BOOTPROTO=bootp
+fi
+
 if [ "${BOOTPROTO}" = "bootp" -o "${BOOTPROTO}" = "dhcp" ]; then
     DYNCONFIG=true
+    [ "${BOOTPROTO}" = bootp ] && DHCP_CLIENT=/sbin/pump
 fi
 
 # load the module associated with that device
@@ -41,6 +53,7 @@ if [ -n "${HWADDR}" ]; then
     FOUNDMACADDR=$(get_hwaddr ${REALDEVICE})
     if [ "${FOUNDMACADDR}" != "${HWADDR}" -a "${FOUNDMACADDR}" != "${MACADDR}" ]; then
 	    net_log $"Device ${DEVICE} has different MAC address than expected, ignoring."
+	    mdv-network-event connection_failure ${DEVICE}
 	    exit 1
     fi
 fi
@@ -49,6 +62,7 @@ fi
 if [ "${TYPE}" = "Bridge" ]; then
       if [ ! -x /usr/sbin/brctl ]; then
 	  net_log $"Bridge support not available: brctl not found"
+	  mdv-network-event connection_failure ${DEVICE}
 	  exit 1
       fi
       if [ ! -d /sys/class/net/${DEVICE}/bridge ]; then
@@ -66,12 +80,22 @@ fi
 
 # If the device is a tap device, create it with tunctl, if available.
 if [ "${TYPE}" = "Tap" ]; then
-      if [ ! -x /usr/sbin/tunctl ]; then
+      if [ ! -x /usr/sbin/tunctl -a ! -x /usr/bin/tunctl ]; then
           net_log  $"Tap support not available: tunctl not found"
+	  mdv-network-event connection_failure ${DEVICE}
           exit 1
       fi
+      # load the correct module if necessary (#54748)
+      if [ ! -c /dev/net/tun ]; then
+          if ! modprobe tun > /dev/null 2>&1; then
+               echo $"No TUN/TAP support available in kernel for device ${DEVICE}"
+               mdv-network-event connection_failure ${DEVICE}
+               exit 1
+          fi
+      fi
+
       [ -n "${OWNER}" ] && OWNER="-u ${OWNER}"
-      /usr/sbin/tunctl ${OWNER} -t ${DEVICE} > /dev/null
+      tunctl ${OWNER} -t ${DEVICE} > /dev/null
 fi
 
 # now check the real state
@@ -81,9 +105,67 @@ is_available ${REALDEVICE} || {
       else
          net_log $"Device ${DEVICE} does not seem to be present, delaying initialization."
       fi
+      mdv-network-event connection_failure ${DEVICE}
       exit 1
 }
 
+# is the device wireless? If so, configure wireless device specifics
+IS_WIRELESS=
+if is_wireless_device ${DEVICE}; then
+    # ralink devices need to be up for wireless-tools to work
+    ip link set dev ${DEVICE} up
+    if [ -n "${daemon}" -o "$MII_NOT_SUPPORTED" = "yes" ]; then
+        # try to trigger association (and always load wireless settings)
+	WIRELESS_CONFIG="wireless.d/$WIRELESS_ESSID"
+	[ -f "$WIRELESS_CONFIG" ] && source "$WIRELESS_CONFIG"
+	. ./ifup-wireless
+        if [ -n "$WIRELESS_WPA_DRIVER" -a -x /usr/sbin/wpa_supplicant -a -f /etc/wpa_supplicant.conf ]; then
+            if wpa_cli -i${DEVICE} status &>/dev/null; then
+                echo "Another wpa_supplicant instance is already running for device $DEVICE"
+            else
+                /usr/sbin/wpa_supplicant -B -i ${DEVICE} \
+                    -c /etc/wpa_supplicant.conf  \
+                    -D ${WIRELESS_WPA_DRIVER}
+            fi
+            if [ "$WIRELESS_WPA_REASSOCIATE" = "yes" ]; then
+                sleep 2
+                wpa_cli reassociate
+            fi
+	fi
+    elif [ -n "$WIRELESS_WPA_DRIVER" ]; then
+        # roaming enabled, on association
+        # source interface parameters related to current ESSID or AP if any
+        WIRELESS_CURRENT_ESSID=`iwgetid -r ${DEVICE}`
+        if [ -n "$WIRELESS_CURRENT_ESSID" ]; then
+            WIRELESS_CONFIG="wireless.d/$WIRELESS_CURRENT_ESSID"
+            if [ ! -f "$WIRELESS_CONFIG" ]; then
+                WIRELESS_CURRENT_AP=`iwgetid -r -a ${DEVICE}`
+                WIRELESS_CONFIG="wireless.d/$WIRELESS_CURRENT_AP"
+            fi
+            if [ -f "$WIRELESS_CONFIG" ]; then
+                source "$WIRELESS_CONFIG"
+            else
+                echo "Wireless device $DEVICE is associated with $WIRELESS_CURRENT_ESSID but configuration is missing"
+            fi
+        else
+            echo "Wireless device $DEVICE is configured with a roaming daemon but isn't associated"
+        fi
+    fi
+    IS_WIRELESS=1
+fi
+
+# DVB Card
+if [ -n "${DVB_ADAPTER_ID}" -a -n "${DVB_NETWORK_DEMUX}" -a -n "${DVB_NETWORK_PID}" ]; then
+       dvbnet -a ${DVB_ADAPTER_ID} -n ${DVB_NETWORK_DEMUX} -p ${DVB_NETWORK_PID}
+fi
+
+# ATMARP protocol support, enabled if ATM_ADDR is defined (VCI.VPI)
+# useful for modems using the atm kernel module (e.g. Speedtouch)
+# and ISP using "RFC 1483 Routed VC MUX" (e.g. Free Degroupe)
+if [ -n "${ATM_ADDR}" -a -x /usr/sbin/atmarpd -a -x /usr/sbin/atmarp ]; then
+      pidof atmarpd >/dev/null 2>&1 || /usr/sbin/atmarpd -b -l syslog >/dev/null 2>&1
+      atmarp -c ${DEVICE} 2>/dev/null
+fi 
 
 # this isn't the same as the MAC in the configuration filename.  It is
 # available as a configuration option in the config file, forcing the kernel
@@ -94,9 +176,6 @@ fi
 if [ -n "${MTU}" ]; then
    ip link set dev ${DEVICE} mtu ${MTU}
 fi
-
-# is the device wireless? If so, configure wireless device specifics
-is_wireless_device ${DEVICE} && . ./ifup-wireless
 
 # slave device?
 if [ "${SLAVE}" = yes -a "${ISALIAS}" = no -a "${MASTER}" != "" ]; then
@@ -177,28 +256,149 @@ if [ -n "${BRIDGE}" ] && [ -x /usr/sbin/brctl ]; then
       exit 0
 fi
 		     
-if [ -n "${DYNCONFIG}" ] && [ -x /sbin/dhclient ]; then
-    if [[ "${PERSISTENT_DHCLIENT}" =  [yY1]* ]]; then
-       ONESHOT="";
+# exec ifplugd daemon at boot if supported
+if [ -n "${daemon}" -a "$MII_NOT_SUPPORTED" != "yes" ]; then
+    IFPLUGD_ARGS="${IFPLUGD_ARGS=-I -b}"
+    exec /sbin/ifplugd $IFPLUGD_ARGS -i $DEVICE
+fi
+
+
+BLURB="# temporary ifup addition"
+
+if [ -n "$DYNCONFIG" -a "XXX$DHCP_CLIENT" = "XXX" ];then
+    if [ -x /sbin/dhclient ];then
+	DHCP_CLIENT=/sbin/dhclient
+	# Remove any temporary references which were previously added to dhclient config
+	if [ -w /etc/dhclient-${DEVICE}.conf -a -x /sbin/dhclient ] ; then
+	    grep -v "$BLURB" /etc/dhclient-${DEVICE}.conf > /etc/dhclient-${DEVICE}.conf.ifupnew 2> /dev/null
+	    cat /etc/dhclient-${DEVICE}.conf.ifupnew > /etc/dhclient-${DEVICE}.conf
+	    rm -f /etc/dhclient-${DEVICE}.conf.ifupnew
+	fi
+    elif [ -x /sbin/dhcpcd ];then
+	DHCP_CLIENT=/sbin/dhcpcd
+    elif [ -x /sbin/pump ];then
+	DHCP_CLIENT=/sbin/pump
+    elif [ -x /sbin/dhcpxd ];then
+	DHCP_CLIENT=/sbin/dhcpxd
+    else 
+	echo $"Can't find a dhcp client"
+	mdv-network-event connection_failure ${DEVICE}
+	exit 1;
+    fi
+fi  
+
+if [ "$DHCP_HOSTNAME" ] && [ "$DOMAINNAME" ]
+then
+	DHCP_HOSTNAME=`echo $DHCP_HOSTNAME | sed -e "s/\.$DOMAINNAME//g"`
+fi
+
+DHCP_ARGS=
+if [ "XXX$DHCP_CLIENT" != "XXX" ];then
+case $(basename $DHCP_CLIENT) in
+    dhcpcd)
+    DHCP_ARGS="--waitip"
+    [ -n "${DHCP_HOSTNAME}" ] && DHCP_ARGS="${DHCP_ARGS} -h ${DHCP_HOSTNAME}"
+    [ "${PEERDNS}" = "no" ] && DHCP_ARGS="${DHCP_ARGS} -C resolv.conf"
+    [ "${PEERGATEWAY}" = "no" ] && DHCP_ARGS="${DHCP_ARGS} -G"
+    [ -n "${DHCP_TIMEOUT}" ] && DHCP_ARGS="${DHCP_ARGS} -t ${DHCP_TIMEOUT}"
+    [ "${NEEDHOSTNAME}" = "no" ] && DHCP_ARGS="${DHCP_ARGS} -C lookup-hostname"
+    if [ "${PEERNTPD}" = "yes" ]; then
+        DHCP_ARGS="${DHCP_ARGS} -o ntp_servers"
     else
-       ONESHOT="-1";
-    fi;
+        DHCP_ARGS="${DHCP_ARGS} -C ntp.conf -O ntp_servers"
+    fi
+    if [ "${PEERYP}" = "yes" ]; then
+        DHCP_ARGS="${DHCP_ARGS} -o nis_domain -o nis_servers"
+    else
+        DHCP_ARGS="${DHCP_ARGS} -C yp.conf -C ypbind -O nis_domain -O nis_servers"
+    fi
+
+    DHCP_ARGS="${DHCP_ARGS} ${DEVICE}"
+    PIDF=/var/run/dhcpcd-${DEVICE}.pid
+    if [[ -f ${PIDF} ]]; then
+        PID=$(cat ${PIDF})
+        if [[ -n ${PID} ]]; then
+            echo "dhcpcd is running, ifdown the interface first"
+            exit;
+        fi
+        /bin/rm -f ${PIDF}; #clear it
+    fi
+    ;;
+    pump)
+    [ -n "$DHCP_HOSTNAME" ] && DHCP_ARGS="-h $DHCP_HOSTNAME"
+    [ "${NEEDHOSTNAME}" = "yes" ] && DHCP_ARGS="$DHCP_ARGS --lookup-hostname"
+    [ "${PEERDNS}" = "no" ] && DHCP_ARGS="$DHCP_ARGS -d"
+    [ "${PEERGATEWAY}" = "no" ] && DHCP_ARGS="$DHCP_ARGS --no-gateway"
+    DHCP_ARGS="$DHCP_ARGS -i $DEVICE"
+    ;;
+    dhcpxd)
+    # dhcpxd don't support NEEDHOSTNAME, PEERGATEWAY
+    [ -n "$DHCP_HOSTNAME" ] && DHCP_ARGS="-H $HOSTNAME"
+    DHCP_ARGS="$DHCP_ARGS --wait $DEVICE"
+    ;;
+    dhclient)
+    if [[ "${PERSISTENT_DHCLIENT}" = [yY1]* ]]; then
+	ONESHOT=
+    else
+	ONESHOT="-1"
+    fi
     generate_config_file_name
     generate_lease_file_name
-    DHCLIENTARGS="${DHCLIENTARGS} -H ${DHCP_HOSTNAME:-${HOSTNAME%%.*}} ${ONESHOT} -q ${DHCLIENTCONF} -lf ${LEASEFILE} -pf /var/run/dhclient-${DEVICE}.pid"
+    DHCP_ARGS="$DHCP_ARGS $ONESHOT -q ${DHCLIENTCONF} -lf ${LEASEFILE} -pf /var/run/dhclient-${DEVICE}.pid $DEVICE"
+    if [ -n "$DHCP_HOSTNAME" ]; then
+	if [ ! -e /etc/dhclient-${DEVICE}.conf ] || ! grep -q "[^# ]*send *host-name" /etc/dhclient-${DEVICE}.conf; then
+	    echo "send host-name \"${DHCP_HOSTNAME}\";  $BLURB" >> /etc/dhclient-${DEVICE}.conf
+	fi
+    fi
+    if [ -n "$DHCP_TIMEOUT" ]; then
+	if [ ! -e /etc/dhclient-${DEVICE}.conf ] || ! grep -q "[^# ]*timeout" /etc/dhclient-${DEVICE}.conf; then
+	    echo "timeout $DHCP_TIMEOUT;  $BLURB" >> /etc/dhclient-${DEVICE}.conf
+	fi
+    fi	
+    ;;
+esac
+fi
+
+# Remove any temporary references which were previously added to dhclient config
+if [ -w /etc/dhclient-${DEVICE}.conf ] && [ -x /sbin/dhclient ] ; then
+   LC_ALL=C grep -v "# temporary MDK ifup addition" /etc/dhclient-${DEVICE}.conf > /etc/dhclient-${DEVICE}.conf.ifupnew 2> /dev/null
+   cat /etc/dhclient-${DEVICE}.conf.ifupnew > /etc/dhclient-${DEVICE}.conf
+   rm -f /etc/dhclient-${DEVICE}.conf.ifupnew
+fi
+		     
+if [ -n "${DYNCONFIG}" ]; then
     echo
     echo -n $"Determining IP information for ${DEVICE}..."
     if [[ "${PERSISTENT_DHCLIENT}" !=  [yY1]* ]] && check_link_down ${DEVICE}; then
 	echo $" failed; no link present.  Check cable?"
+	ip link set dev ${DEVICE} down >/dev/null 2>&1
+	mdv-network-event connection_failure ${DEVICE}
 	exit 1
     fi
 
     ethtool_set
 
-    if /sbin/dhclient ${DHCLIENTARGS} ${DEVICE} ; then
+    mdv-network-event dhcp_request ${DEVICE}
+    if $DHCP_CLIENT $DHCP_ARGS ; then
+        mdv-network-event dhcp_success ${DEVICE}
 	echo $" done."
     else
+        mdv-network-event dhcp_failure ${DEVICE}
+	# Associate a zeroconf IP address to an alias of the interface
+	if [ -x /sbin/zcip ]; then
+            mdv-network-event zcip_request ${DEVICE}
+	    if /sbin/zcip -s -i $DEVICE:${ZEROCONF_ALIAS_NUMER=9}; then
+                mdv-network-event zcip_success ${DEVICE}
+		echo $" done."
+		if [ -x /etc/init.d/tmdns ]; then
+		    /etc/init.d/tmdns reload > /dev/null 2>&1
+		fi
+		exit 0
+	    fi
+	fi
+        mdv-network-event zcip_failure ${DEVICE}
 	echo $" failed."
+	mdv-network-event connection_failure ${DEVICE}
 	exit 1
     fi
 # end dynamic device configuration
@@ -217,6 +417,7 @@ else
    
     if ! ip link set dev ${REALDEVICE} up ; then
 	net_log $"Failed to bring up ${DEVICE}."
+	mdv-network-event connection_failure ${DEVICE}
 	exit 1
     fi
 
@@ -236,6 +437,7 @@ else
        SRC=
     fi
     
+    if [ "${REALDEVICE}" != "lo" ]; then
     # set IP address(es)
     for idx in {0..256} ; do
 	if [ -z "${ipaddr[$idx]}" ]; then
@@ -246,6 +448,7 @@ else
             [ "${REALDEVICE}" != "lo" ] && [ "${arpcheck[$idx]}" != "no" ] && \
             if ! /sbin/arping -q -c 2 -w 3 -D -I ${REALDEVICE} ${ipaddr[$idx]} ; then
                 net_log $"Error, some other host already uses address ${ipaddr[$idx]}."
+                mdv-network-event connection_failure ${DEVICE}
                 exit 1
             fi
 
@@ -266,11 +469,18 @@ else
             /sbin/arping -q -U -c 1 -I ${REALDEVICE} ${ipaddr[$idx]} ) > /dev/null 2>&1 < /dev/null &
         fi
     done
+    fi
 
     # Set a default route.
     if [ "${DEFROUTE}" != "no" ] && [ -z "${GATEWAYDEV}" -o "${GATEWAYDEV}" = "${REALDEVICE}" ]; then
 	# set up default gateway. replace if one already exists
 	if [ -n "${GATEWAY}" ] && [ "$(ipcalc --network ${GATEWAY} ${netmask[0]} 2>/dev/null)" = "NETWORK=${NETWORK}" ]; then
+	    if [ -n "${ATM_ADDR}" -a -x /usr/sbin/atmarpd -a -x /usr/sbin/atmarp ]; then
+		ip link set dev ${REALDEVICE} down
+		ip link set dev ${REALDEVICE} up
+		sleep 2
+		atmarp -s ${GATEWAY} ${ATM_ADDR} null 2>/dev/null
+	    fi 
 	    ip route replace default ${METRIC:+metric $METRIC} \
 		via ${GATEWAY} ${WINDOW:+window $WINDOW} ${SRC} \
 		${GATEWAYDEV:+dev $GATEWAYDEV} ||
@@ -285,7 +495,7 @@ else
 fi
 
 # Add Zeroconf route.
-if [ -z "${NOZEROCONF}" -a "${ISALIAS}" = "no" -a "${REALDEVICE}" != "lo" ]; then
+if [ "${NOZEROCONF}" != "yes" -a "${ISALIAS}" = "no" -a "${REALDEVICE}" != "lo" ]; then
     ip route add 169.254.0.0/16 dev ${REALDEVICE} metric $((1000 + $(cat /sys/class/net/${REALDEVICE}/ifindex))) scope link
 fi
 
